version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: